Update static.yml

diff --git a/.github/workflows/static.yml b/.github/workflows/static.yml
--- a/.github/workflows/static.yml
+++ b/.github/workflows/static.yml
@@ -32,7 +32,7 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Inject Unsplash API Key into JavaScript
-      # Make the secret available as an environment variable for this step
+      # Make UNSPLASH secret available as an environment variable for this step
         env:
           UNSPLASH_API_KEY_SECRET: ${{ secrets.__UNSPLASH_API_KEY__}} 
         run: |
@@ -47,7 +47,23 @@ jobs:
           echo "Injecting API Key into $JS_FILE..."
           sed -i "s|__UNSPLASH_API_KEY__|$UNSPLASH_API_KEY_SECRET|g" "$JS_FILE"
           echo "API Key injection complete."
-        
+          
+      # Make IMDB secret available as an environment variable for this step
+          env:
+          OMDB_API_KEY_SECRET: ${{ secrets.__OMDB_API_KEY__}} 
+        run: |
+    
+          JS_FILE="movie-search/src/services/api.js" 
+
+          if [ ! -f "$JS_FILE" ]; then
+            echo "Error: $JS_FILE not found. Please check the path."
+            exit 1
+          fi
+
+          echo "Injecting API Key into $JS_FILE..."
+          sed -i "s|__OMDB_API_KEY__|$OMDB_API_KEY_SECRET|g" "$JS_FILE"
+          echo "API Key injection complete."
+          
       - name: Setup Pages
         uses: actions/configure-pages@v5
       - name: Upload artifact
